Pandas tutorial
pandas is an open source.BSD-licensed library providing high_performance,easy to use data structure and data anlysis tools for the python programming language
*what is data frame?
*what is data science?
*different operation in pandas

In [1]:
## First step is to import pandas
import pandas as pd
import numpy as np

In [2]:
## playing with dataframe it mean convert data as like excel sheet
df=pd.DataFrame(np.arange(0,30).reshape(6,5),index=['Row1','Row2','Row3','Row4','Row5','row6'],columns=["colums1","colums2","colums3","colums4","colums5"])
df.head()

      colums1  colums2  colums3  colums4  colums5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19
Row5       20       21       22       23       24

In [4]:
df.to_csv('test1.csv')

In [5]:
## accessing the elements
## 1. loc 2. .iloc here it indicate index location mean both we see row and colum
df.loc['Row2']## its just consider as csv
##type(df.loc['Row2'])##pandas.core.series.Series

colums1    5
colums2    6
colums3    7
colums4    8
colums5    9
Name: Row2, dtype: int64

In [6]:
## iloc
df.iloc[:,:]
##type(df.iloc[0:,0:2])##pandas.core.frame.DataFrame

      colums1  colums2  colums3  colums4  colums5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19
Row5       20       21       22       23       24
row6       25       26       27       28       29

In [7]:
#convert dataframes into array
df.iloc[:,1:].values #.shape #this values convert dataframes to an array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29]])

In [ ]:
#df.isnull().sum()
df

      colums1  colums2  colums3  colums4  colums5
Row1        0        1        2        3        4
Row2        5        6        7        8        9
Row3       10       11       12       13       14
Row4       15       16       17       18       19
Row5       20       21       22       23       24
row6       25       26       27       28       29

In [4]:
df['colums1'].value_counts()

colums1
0     1
5     1
10    1
15    1
20    1
25    1
Name: count, dtype: int64